global:
  storageClass: "storage-todo"
  app: "todo-app"
app:
  name: todo-app
  ports:
    containerPort: 5000
  image: "public.ecr.aws/c7o8u9c1/nathan-todo:1.0.12"
  replicaCount: 1
  appName: todo-app
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
      ephemeralStorage: "1Gi"
    limits:
      memory: "128Mi"
      cpu: "500m"
      ephemeralStorage: "2Gi"
  env:
    confMapRef:
      name: mongo-config
    mongoURL:
      name: mongo-url
      secretKeyRef:
        name: mongo-secret
        key: mongo-url
ingress:
  name: todo-ingress
  labels:
    name: todo-ingress
  annotations:
    ingressClass: "nginx"
  hosts:
    host: nathancowsay.tk
    pathType: Prefix
    path: "/"
    service:
      name: todo-service
      port: 5000
  tls: []
secrets:
  name: mongo-secret
  type: Opaque
  data:
    mongoUser: bW9uZ291c2Vy #mongouser
    mongoPassword: bW9uZ29wYXNzd29yZA== #mongopassword
    mongoUrl: "bW9uZ29kYjovL21vbmdvdXNlcjptb25nb3Bhc3N3b3JkQGFyZ28tY3JtLW1vbmdvZGItMC5hcmdvLWNybS1tb25nb2RiLWhlYWRsZXNzOjI3MDE3LGFyZ28tY3JtLW1vbmdvZGItMS5hcmdvLWNybS1tb25nb2RiLWhlYWRsZXNzOjI3MDE3LGFyZ28tY3JtLW1vbmdvZGItMi5hcmdvLWNybS1tb25nb2RiLWhlYWRsZXNzOjI3MDE3L3RvZG8="
config:
  name: mongo-config
  data:
    mongoUri: "mongodb://mongouser:mongopassword@todo-mongodb-0.todo-mongodb-headless:27017,argo-todo-mongodb-1.argo-todo-mongodb-headless:27017,argo-todo-mongodb-2.argo-todo-mongodb-headless:27017/todo"
    logLevel: "info"
    PERSISTENCE: "true"
service:
  name: todo-service
  type: ClusterIP
  ports:
    protocol: TCP
    port: 5000
    targetPort: 5000
storage:
  name: storage-todo
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp2
    fstype: ext4
    replicationType: none
