apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: {{ .Values.secrets.type }}
data:
  mongo-user: "{{ .Values.secrets.data.mongoUser }}"
  mongo-password: "{{ .Values.secrets.data.mongoPassword }}"
  mongo-url: "{{ .Values.secrets.data.mongoUrl }}"